### ISSUE TITLE
Include ps4eye/ps4eye's firmware into ROS package 

### ISSUE THREAD

**Issue by longjie** [longjie/ps4eye#11]
Need to include ps4eye_init.py and firmware.bin into this package from https://github.com/ps4eye/ps4eye .
The license is not mentioned. Need to display clearly that both file are from https://github.com/ps4eye/ps4eye.

**Comment by longjie** [comment]
branch include_ps4eye_firmware should work, only if we make symlink:

```
$ sudo ln -s /home/tajima/Codes/ros/hydro/install/share/ps4eye/etc/99-ps4eye.rules /etc/udev/rules.d/
```

I know how to do it in .deb, but how can I do that in ROS package?

**Comment by k-okada** [comment]
By looking at -> 
https://github.com/yujinrobot/kobuki_core/blob/indigo/kobuki_ftdi/CMakeLists.txt
we should create script like 
https://github.com/yujinrobot/kobuki_core/blob/indigo/kobuki_ftdi/scripts/create_udev_rules 
and ask user to install them.

I think the problem is if ros-jade-ps4eye and ros-indigo-ps4eye have same 
file it will conflict and `apt-get install` fails to  install.

## 

◉ Kei Okada

**Comment by longjie** [comment]
It's good example. I will follow this way.

**Comment by longjie** [comment]
include_ps4eye_firmware でプラグアンドプレイでps4eyeが使えるようになったはずです。

```
$ rosrun ps4eye create_udev_rules
```

を最初に一度だけやる必要があります。
mergeするまえに、debにしても正しく動くことを確認したいのですが、どのようにすればいいのでしょうか？

**Comment by longjie** [comment]
I found good anser at:
http://answers.ros.org/question/173804/generate-deb-from-ros-package/

I made .deb and checked it correctly.
I will merge the branch and release it soon.
